@startuml

skinparam classAttributeIconSize 0

class Voiture {
    - plaqueImmatriculation : Int [Unique]
    - marque : String
    - couleur : String
}

class Parking {
    - id_parking : Int [Unique]
    - ville : String
    - place_parc : Int
    - voiture : List<Voiture>
}

Voiture "1" --> "1" Parking : "belongs to"
Parking "1" --> "*" Voiture : "has"
@enduml