@startuml

entity "Voiture" {
  * plaqueImmatriculation : Int <<PK>>
  marque : String
  couleur : String
  parking_id : Int <<FK>>
}

entity "Parking" {
  * id_parking : Int <<PK>>
  ville : String
  place_parc : Int
}

Voiture }o--|| Parking : belongs to
@enduml
